openapi: 3.0.3
info:
  title: SIM Swap
  description: |+
    SIM Swap API provides the customer the ability to obtain information on any recent SIM pairing change
     related to the Userâ€™s mobile account. 

    The API provided 2 operations:

    - POST retrieveSimSwapDate : provide timestamp of latest sim swap,

    - POST checkSimSwap: check if sim swap has been performed during a past period (defined in the request with 'age' attribute).
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.3.0
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/
security:
  - oAuth2ClientCredentials: []
  - BasicAuth: []
  - apiKey: []
  - three_legged:
    - checkSimSwap
    - getSimSwapDate
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: sim-swap/v0
        description: Base path for the simSwap API
paths:
  /retrieve-date:
    post:
      tags:
        - Retrieve SIM swap date
      description: Get timestamp of last MSISDN <-> IMSI pairing change for a mobile user account provided with MSIDN.
      operationId: createSimSwapDateRequest
      requestBody:
        description: |+
          Create a simSwap date request. A MSISDN identifier is required.        
        content :
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSimSwapDate"
        required: true
      responses:
        "200":
          description: Contains information about sim swap change
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimSwapInfo"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic400:
                  summary: Schema validation failed
                  value: 
                    code: INVALID_INPUT
                    message: "Schema validation failed at  ..."
                MsisdnRequired:
                  summary: msisdn is required as part of ueId
                  value: 
                    code: INVALID_INPUT
                    message: "Expected property is missing: msisdn"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              example:
                code: CONFLICT
                message: "Another resquest is created for the same UE"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              example:
                code: INTERNAL
                message: "Session could not be created"
        "503":
          $ref: "#/components/responses/Generic503" 
  /checkSimSwap:
    post:
      tags:
      - Check simSwap
      description: Manage request and response for a simSwap check for a mobile user account provided with MSIDN.
      operationId: createCheckSimSwap
      requestBody:
        description: |+
          Create a Check simSwap request. A MSISDN identifier and age are required.        
        content :
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCheckSimSwap"
        required: true
      responses:
        "200":
          description: check simSwap created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckSimSwapInfo"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic400:
                  summary: Schema validation failed
                  value: 
                    code: INVALID_INPUT
                    message: "Schema validation failed at  ..."
                MsisdnRequired:
                  summary: msisdn is required as part of ueId
                  value: 
                    code: INVALID_INPUT
                    message: "Expected property is missing: msisdn"
                AgeRequired:
                  summary: msisdn is required as part of ueId
                  value: 
                    code: INVALID_INPUT
                    message: "Expected property is missing: age"                    
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              example:
                code: CONFLICT
                message: "Another resquest is created for the same UE"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              example:
                code: INTERNAL
                message: "Session could not be created"
        "503":
          $ref: "#/components/responses/Generic503"
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
    BasicAuth:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      description: API key to authorize requests
      name: apikey
      in: query
    three_legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/authorize
          tokenUrl: https://auth.example.com/token
          scopes:
            simSwapCheck: checkSimSwap
            simSwapDate: getSimSwapDate
  schemas:
    SimSwapInfo:
      type: object
      properties:
        sim_change: 
          type: string
          format: date-time
          description: timestanp of latest SIM swap performed

    CheckSimSwapInfo:
      type: object
      properties:
        swapped:
          type: boolean
          description: Indicates whether the SIM card has been swapped during the
            delay. Should be valued only if an age is passed in the request.
    MSISDN:
      type: string
      pattern: '^\+?[0-9]{5,15}$'
      example: "123456789"
      description: Subscriber number in E.164 format (starting with country code). Optionally prefixed with '+'.
    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
    CreateCheckSimSwap:
      type: object
      required:
        - msisdn
        - age
      properties:
        msisdn:
          $ref: "#/components/schemas/MSISDN"
        age:
          type: integer
          example: 240
          description: |
            Delay in hours to be checked for simswap.
          format: int32
          minimum: 1
          maximum: 24000
          default: 240
    CreateSimSwapDate:
      type: object
      required:
        - msisdn
      properties:
        msisdn:
          $ref: "#/components/schemas/MSISDN"
  responses:
    Generic400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: INVALID_INPUT
            message: "Schema validation failed at  ..."
    Generic401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: UNAUTHORIZED
            message: "Authorization failed: ..."
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: FORBIDDEN
            message: "Operation not allowed: ..."
    Generic503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            code: SERVICE_UNAVALABLE
            message: "Service unavailable"


